name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ruby_version: ["2.7", "3.0", "3.1", "3.2", "3.3"]
        os: ["ubuntu-latest","windows-latest","macos-latest"]
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@master
        with:
          ruby-version: ${{ matrix.ruby_version }}
      - run: "bundle install"
      - run: "bundle exec rake pact:spec"
      - run: "bundle exec rake pact:spec:v1"
      - run: cat spec/pacts/test_message_consumer-test_message_producer.json
      - run: bundle exec rake pact:verify
        shell: bash
        if: matrix.os != 'windows-latest'
      # - run: "ruby.exe -S pact verify --pact-helper ./spec/service_consumers/pact_helper.rb --pact-uri ./spec/pacts/test_message_consumer-test_message_producer.json"
        # if: matrix.os == 'windows-latest'
      - run: bundle exec rake pact:verify:v2
        if: matrix.os != 'windows-latest' # no kafka on windows